# Copyright (c) 2025 Analog Devices, Inc.
# SPDX-License-Identifier: MIT

CONFIG_ADC=y
CONFIG_LOG=y
CONFIG_LIBIIO_LOG_LEVEL_ERR=y

CONFIG_ADC_AD7124=y
CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_ETH_ADIN2111=y

CONFIG_LIBIIO_IIO_DEVICE_THERMOCOUPLE=y