# Copyright (c) 2025 Analog Devices, Inc.
# SPDX-License-Identifier: MIT

CONFIG_ADC=y
CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_LIBIIO_IIO_DEVICE=y
CONFIG_LIBIIO_IIO_DEVICE_ADC=y

# CONFIG_LOG=y
# CONFIG_LIBIIO_LOG_LEVEL_DBG=y
# CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_CACHE_MANAGEMENT=y
CONFIG_NOCACHE_MEMORY=y
